# Generated by Django 3.1.7 on 2021-02-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='descripcion',
            new_name='description',
        ),
    ]
